export let en = {
  years: 'years',
  objMain: 'Objectives',
  objText: 'Keep learning new technologies and give my best in every project I get involved',
  interests: 'Interest areas',
  projects: 'Sites',
  aboutMe: 'I consider myself proactive, enthusiastic and self-taught, I am someone who loves to learn and seeks new challenges and opportunities always giving my best to contribute with my experience in a leading company',
  knowTitle: 'Technical expertise',
  codellegeText: 'Consists of several sujects, starting with Orientation where we learn about emotional intelligence and conflict resolution, another is Entrepreneurship where ideas and business models are seen, also English and web developing where we learn about HTML, CSS, JavaScript and NodeJS',
  workText: 'I have had the opportunity to work at Softtek on many internal projects with great dev teams, analyzing, developing, delivering and supporting applications web, mobiles and APIs using Vue, React, MongoDB, Express, SPFX, GitLab CI, Compose, TypeScript ...',
  en1: 'reading',
  en2: 'writing',
  en3: 'listening',
  en4: 'speaking',
}

export let es = {
  years: 'años',
  objMain: 'Objetivos',
  objText: 'Seguir aprendiendo nuevas tecnologías y dar lo mejor de mi en cada proyecto en que me involucre',
  interests: 'Áreas de interés',
  projects: 'Sitios',
  aboutMe: 'Me considero proactivo, entusiasta y autodidacta, soy alguien que ama aprender y busca nuevos retos y oportunidades siempre dando lo mejor para contribuir con mi experiencia en una compañia lider',
  knowTitle: 'Conocimientos técnicos',
  codellegeText: 'Se llevan varias clases, una es Orientación donde vemos inteligencia emocional y resolución de conflictos, otra es Emprendimiento donde se ven ideas y modelos de negocio, tambien Inglés y programación web donde se aprende HTML, CSS, JavaScript y NodeJS',
  workText: 'He tenido la oportunidad de trabajar en Softtek en muchos proyectos internos en equipo, analizando, desarrollando, entregando y dando soporte a aplicaciones web, mobiles y APIs usando Vue, React, MongoDB, Express, SPFX, GitLab CI, Compose, TypeScript...',
  en1: 'leer',
  en2: 'escribir',
  en3: 'escuchar',
  en4: 'hablar',
}
