name: Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --production --ignore-optional --pure-lockfile --non-interactive
    - run: yarn build
    - run: cp CNAME build/CNAME
    - uses: LuisEnMarroquin/gh-pages-publish@v2.3.2
      with:
        FOLDER: build
        SSHKEY: ${{ secrets.SSH }}
