name: Pipeline Main

on:
  push:
    branches:
    - disabled-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: NPM install
      run: npm ci --omit=dev --omit=optional
    - name: Build project
      run: npm run build
    - name: Run in background
      run: node server.js &
    - name: Create PDFs
      run: node genPDF.js
      working-directory: build/
    - uses: LuisEnMarroquin/gh-pages-publish@v2.4.4
      with:
        FOLDER: build
        SSHKEY: ${{ secrets.SSH }}
